src/main/java/entities/Game.java, src/main/java/entities/ObservableGame.java
…servableGame interface, and added @Override to these methods in Game. Changed changeCurrentTurn to now be public. This allows for observers of an ObservableGame to access/get elements required for the UI.
=> Added methods to ObservableGame

src/main/java/use_cases/GameState.java, src/test/java/use_cases/GameStateTest.java
Created a GameState class which observes a given Game. It contains information needed for the User to see in the UI such as the current Player and their Cards, the last Card played, the rest of the Players in the Game and their number of Cards, and whether or not the Game has a winner. These attributes are updated whenever Game notifies it's observers, this logic is to be implemented in the interactor. This class comes with full documentation and a test class. 
One thing that may be added here in the future is if the player can pick up a Card, however this logic I believe should be delegated to the interactor.
=> 7 feature 7 getgamestate use case class

src/main/java/entities/ComputerPlayerFactory.java, src/main/java/entities/HumanPlayerFactory.java, src/main/java/entities/PlayerFactory.java
Add the necessary player factories to better facilitate creating the players once the game is started. Persistence for stats and checking if a player name has already been taken when creating a player have yet to be implemented.
=> 5 feature 5 player factories

src/main/java/controllers/PlayerGameController.java, src/main/java/entities/ComputerPlayer.java, src/main/java/entities/Game.java, src/main/java/entities/Player.java, src/main/java/use_cases/PlayerGameInputBoundary.java, src/main/java/use_cases/PlayerGameInteractor.java, src/main/java/use_cases/PlayerGameRequestModel.java, src/main/java/use_cases/PlayerGameResponseModel.java, src/test/java/entities/ComputerPlayerTest.java, src/test/java/entities/GameTest.java, src/test/java/use_cases/GameStateTest.java, src/test/java/use_cases/PlayerGameInteractorTest.java, src/test/java/use_cases/PlayerGameResponseModelTest.java
Created the model and controller part of playing a Card for MVC. Input comes to the controller on if a card should be played, if the turn should be skipped, or the User/Player pick up a card. The controller packages this into a requestModel object which is used by the inputBoundary object, which is an attribute of the controller, to create a responseModel object in which the information in it is to be shown to the User eventually. InputBoundary is an interface which is implemented by the interactor, which contains logic for picking up a card, putting one down, skipping the turn, as well as the logic of the ComputerPlayer.
The expectation is Main will create this controller with perhaps the inputBoundary once for each Game instance, and each time a User presses a button, this information …
=> 4 feature 4 play card feature

src/main/java/entities/Card.java, src/main/java/entities/StandardDeck.java, src/test/java/entities/GameTest.java, src/test/java/use_cases/PlayerGameInteractorTest.java, src/test/java/use_cases/PlayerGameResponseModelTest.java
For ease of displaying cards on the window when the game is being played, the card values were updated. This meant updating some Javadocs and code in some test cases.
=> Update card values

src/main/java/ui/components/NavigationButton.java, src/main/java/ui/windows/CardLayoutManager.java, src/main/java/ui/windows/ICardLayoutManager.java, src/main/java/ui/windows/PaneDelegator.java
Adds classes to handle navigation between windows.
=> Window management

src/main/java/ui/enums/Rank.java, src/main/java/ui/enums/Suit.java
Card suit and rank constants for consistent naming
=> Add Card enums

src/main/java/ui/factories/GameWindowFactory.java, src/main/java/ui/factories/StatsWindowFactory.java, src/main/java/ui/factories/WindowFactory.java
Title. not every window has a factory right now, will be made later
=> Add some window factories

src/main/java/ui/windows/RulesDisplay.java, src/main/java/ui/windows/StatsDisplay.java
Improving on the display and font size for the rules and statistics pages. Formatting was also improve for readability and flow.
=> Better displays

src/main/java/ui/components/DrawnCard.java, src/main/java/ui/components/DrawnHand.java, src/main/java/ui/windows/CardDelegator.java, src/main/java/ui/windows/GameController.java, src/main/java/ui/windows/GameDelegator.java, src/main/java/ui/windows/GameDisplay.java, src/main/java/ui/windows/GameDrawDelegator.java, src/main/java/ui/windows/GamePlayDelegator.java, src/main/java/ui/windows/GameSkipDelegator.java, src/main/java/ui/windows/GameWindow.java
Add game GUI classes. controller is not linked with anything yet so future PRs will address that.
=> Game window

src/main/java/controllers/PlayerGameController.java, src/main/java/entities/Card.java, src/main/java/entities/Game.java, src/main/java/entities/StandardDeck.java, src/main/java/enums/Rank.java, src/main/java/enums/Suit.java, src/main/java/enums/TurnAction.java, src/main/java/ui/components/DrawnCard.java, src/main/java/ui/components/DrawnHand.java, src/main/java/ui/windows/GameController.java, src/main/java/ui/windows/GameDisplay.java, src/main/java/use_cases/CardResponseModel.java, src/main/java/use_cases/PlayerGameInteractor.java, src/main/java/use_cases/PlayerGameRequestModel.java, src/main/java/use_cases/PlayerGameResponseModel.java, src/test/java/entities/CardTest.java, src/test/java/entities/ComputerPlayerTest.java, src/test/java/entities/GameTest.java, src/test/java/entities/PlayerTest.java, src/test/java/use_cases/PlayerGameInteractorTest.java, src/test/java/use_cases/PlayerGameResponseModelTest.java
Refactor most classes and tests using Strings for card suits and rank. Note that certain tests that use bogus card values, e.g. new Card("Test", "17") have currently not been updated since I did not know an appropriate replacement for all of them.
=> Enum refactor

src/main/java/controllers/GameCreationController.java, src/main/java/ui/windows/CreationDisplay.java, src/main/java/ui/windows/CreationWindow.java
I created the window (GameCreationWindow) and display (GameCreationDisplay) for the game creation screen. If valid input is given when the "Play Game" button is pressed, the window will switch to the Game window where a Game has been created for the User(s) to play.
=> 47 feature 18 game creation window

src/main/java/ui/factories/GameWindowFactory.java, src/main/java/ui/factories/StatsWindowFactory.java, src/main/java/ui/factories/WindowFactory.java, src/main/java/ui/windows/StatsController.java, src/main/java/ui/windows/StatsDelegator.java, src/main/java/ui/windows/StatsDisplay.java, src/main/java/ui/windows/StatsDisplayData.java, src/main/java/use_cases/PlayerGameInteractor.java
Edited the stats UI files to match the stats we store for each player.
=> 36 misc 8 edit statistics UI

src/main/java/ui/components/DrawnHand.java, src/main/java/ui/windows/MenuDisplay.java, src/main/java/ui/windows/StatsDisplay.java
Adding in a title to the home page/main menu. Fixed fonts and layout of the StatsDisplay class that somehow got deleted.
=> Main menu title

src/main/java/ui/windows/game/GameDisplay.java
Solves [this issue](https://github.com/CSC207-2023Y-UofT/course-project-crazy-cards/issues/61). Displays and updates the current card at play.
=> Current card display

src/main/java/Main.java, src/main/java/ui/factories/CreatorWindowFactory.java, src/main/java/ui/factories/GameWindowFactory.java, src/main/java/ui/factories/StatsWindowFactory.java, src/main/java/ui/windows/creation/CreationDisplay.java, src/main/java/ui/windows/creation/CreationWindow.java, src/main/java/ui/windows/game/GameController.java, src/main/java/ui/windows/stats/StatsController.java
Modify factories and controllers so they are initialized with the necessary data to function. Fix Main.java's pvsm entrypoint so the program runs in a clean way with no hacks. Depends on classes/interfaces from #63.
=> Fix entrypoint

src/main/java/Main.java, src/main/java/enums/WindowName.java, src/main/java/ui/factories/HowtoWindowFactory.java, src/main/java/ui/windows/howto/HowtoDisplay.java, src/main/java/ui/windows/howto/HowtoWindow.java, src/main/java/ui/windows/menu/MenuDisplay.java, src/main/java/ui/windows/rules/RulesDisplay.java
Resolves #69 by adding a how to play page to the main menu/title page.
=> How to play page

src/main/java/Main.java, src/main/java/ui/windows/menu/MenuDisplay.java
Resolves #74, deleted unused imports, and added a line of code that was missed from the PR for #69, the how to play page.
=> Update main class

src/main/java/entities/Card.java, src/main/java/entities/CustomDeck.java, src/main/java/entities/DeckGenerationParameters.java, src/main/java/entities/EffectGenerationParameters.java, src/main/java/entities/ForceDrawEffect.java, src/main/java/entities/Game.java, src/main/java/entities/GameAccess.java, src/main/java/entities/GameManager.java, src/main/java/entities/Player.java, src/main/java/entities/RandomRankEffect.java, src/main/java/entities/RandomSuitEffect.java, src/main/java/entities/ReverseEffect.java, src/main/java/entities/SkipTurnEffect.java, src/main/java/entities/SpecialEffect.java, src/main/java/entities/StandardDeck.java, src/main/java/use_cases/PlayerGameInteractor.java
Add functionality for preset and customizable decks and card effects.
=> Card effects

src/main/java/database/CSVDatabase.java
Made it so CSVWriter writes to the same file as the other writers (doesn't create new one) as well as it doesn't write the quotation marks into the file.
=> Fixed last bug in CSVDatabase (it was deleting some stats)

src/main/java/entities/Game.java
Modified Game.isValidCard() to check if "card"'s special effect is null or not as to fix the NullPointerException.
=> Bug fix: NullPointerException in Game.isValidCard()

src/test/java/use_cases/PlayerGameInteractorTest.java
Deleted duplicate methods that came from merge coniflict in 90-misc-18
=> deleted duplicate methods.

src/main/java/Main.java, src/main/java/controllers/GameController.java, src/main/java/controllers/data_objects/GameDisplayData.java, src/main/java/entities/game_logic/Game.java, src/main/java/entities/game_logic/GameAccess.java, src/main/java/entities/game_logic/GameManager.java, src/main/java/ui/components/DrawnCard.java, src/main/java/ui/components/DrawnHand.java, src/main/java/ui/windows/game/CardDelegator.java, src/main/java/ui/windows/game/GameDisplay.java, src/main/java/ui/windows/howto/HowtoDisplay.java, src/main/java/ui/windows/rules/RulesDisplay.java, src/main/java/use_cases/GameState.java, src/main/java/use_cases/PlayerGameInteractor.java, src/main/java/use_cases/PlayerGameResponseModel.java
make user interface more interactive, cards now respond to selection and game notifies user of choice validity (e.g. whether a card is valid, whether they can skip), + overall improvement of aesthetics
=> UI updates
